# 项目配置定义
my:
  name: my-site
  version: 1.0.0
spring:
  profiles:
    active: localTest
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
# 系统文件上传服务配置
upload:
  type: local
  local:
    path: ./upload