spring:
  cache:
    type: caffeine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_site?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: sa
    password: sa
    hikari:
      pool-name: hikari
      minimum-idle: 20
      maximum-pool-size: 200
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.ming.core.orm.MyNamingStrategy
      #        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      #        physical-naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      #        physical-naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      #      create 启动时删数据库中的表，然后创建，退出时不删除数据表
      #      create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
      #      update 如果启动时表格式不一致则更新表，原有数据保留
      #      validate 项目启动表结构进行校验 如果不一致则报错
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          # java.sql.SQLFeatureNotSupportedException: 这个 org.postgresql.jdbc.PgConnection.createClob() 方法尚未被实作。
          use_jdbc_metadata_defaults: false
        format_sql: true
    database: mysql
    # 关闭延迟处理
  #    open-in-view: false
  freemarker:
    cache: false
    expose-session-attributes: true
    expose-request-attributes: true
    expose-spring-macro-helpers: true
  data:
    jpa:
      repositories:
        # jpa 仓库引导模式  default:在容器初始化时候加载  lazy:在相关bean调用时加载   deferred:在触发contextRefresh时加载
        bootstrap-mode: lazy
server:
  http:
    port: 8080
