spring:
  profiles:
    active: default
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test_db
    username: sa
    password: sa
  liquibase:
    enabled: false

# 项目配置定义
my:
  name: my-site
  version: 1.0.0