
<!-- 页脚 -->
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="footer-text">备案号：XXXXXXX</span>
        <span class="footer-text">版权所有 &copy; 2023</span>
    </div>
</footer>

<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/blog/main.min.js"></script>
